# Generated by Django 5.0.4 on 2024-04-24 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinanciamentoImovel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("valor_imovel", models.DecimalField(decimal_places=2, max_digits=10)),
                ("entrada", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prazo_meses", models.IntegerField()),
            ],
        ),
    ]
