# Generated by Django 5.0.4 on 2024-04-25 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FinanciamentoVeiculo",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("valor_veiculo", models.DecimalField(decimal_places=2, max_digits=10)),
                ("entrada", models.DecimalField(decimal_places=2, max_digits=10)),
                ("prazo_meses", models.IntegerField()),
            ],
        ),
    ]
